// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL07qbHCOmTaMIWm1Woz47EQnk3fR7dUU',
    appId: '1:439176625039:web:0d41af68c43f24c63ba9fa',
    messagingSenderId: '439176625039',
    projectId: 'employee-management-fbfc4',
    authDomain: 'employee-management-fbfc4.firebaseapp.com',
    storageBucket: 'employee-management-fbfc4.firebasestorage.app',
    measurementId: 'G-NW0L6EG9X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVoVXq6OYrjj9BHMr5SsRYXs7r4bwgzi4',
    appId: '1:439176625039:android:6ea047c6f27483973ba9fa',
    messagingSenderId: '439176625039',
    projectId: 'employee-management-fbfc4',
    storageBucket: 'employee-management-fbfc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvR1jpch6vpDyOhZhkEwcsHN_oKuxtcuM',
    appId: '1:439176625039:ios:f7204239f158086f3ba9fa',
    messagingSenderId: '439176625039',
    projectId: 'employee-management-fbfc4',
    storageBucket: 'employee-management-fbfc4.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvR1jpch6vpDyOhZhkEwcsHN_oKuxtcuM',
    appId: '1:439176625039:ios:f7204239f158086f3ba9fa',
    messagingSenderId: '439176625039',
    projectId: 'employee-management-fbfc4',
    storageBucket: 'employee-management-fbfc4.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL07qbHCOmTaMIWm1Woz47EQnk3fR7dUU',
    appId: '1:439176625039:web:8284fc8e8b7a310c3ba9fa',
    messagingSenderId: '439176625039',
    projectId: 'employee-management-fbfc4',
    authDomain: 'employee-management-fbfc4.firebaseapp.com',
    storageBucket: 'employee-management-fbfc4.firebasestorage.app',
    measurementId: 'G-FWN4045PQR',
  );
}
